---
- hosts: all
  become: yes
  tasks:
   - name: Create deployment directory
     file:
       path: /tmp/cicd-demo
       state: directory
   - name: Copy deployment file
     copy:
       src: deployment.txt
       dest: /tmp/cicd-demo/deployment.txt
   - name: Verify deployment
     shell: cat /tmp/cicd-demo/deployment.txt
     register: output
   - debug:
       var: output.stdout
