---
- hosts: all
  become: yes
  tasks:
   - name: Create demo folder
     file:
       path: /tmp/cicd-demo
       state: directory
       mode: '0755'
   - name: Copy website
     copy:
       src: index.html
       dest: /tmp/cicd-demo/index.html
   - name: Start Python web server
     shell: |
       nohup python3 -m http.server 8080 --directory /tmp/cicd-demo > /tmp/web.log 2>&1 &
