- hosts: all
  vars:
   ansible_user: Zeta_82
   ansible_password: Zensar@7654321
   ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
   - name: Copy deployment file
     copy:
       src: deployment.txt
       dest: /tmp/cicd-demo/deployment.txt
